### ISSUE TITLE
IP Allocation Issues

### ISSUE THREAD

**Issue by andrewpurdin** [aws/amazon-vpc-cni-plugins#42]
Hello. We have been seeing an issue intermittently where pods will become stuck in container creating with the following error or similar:
```
Warning  FailedCreatePodSandBox  56m                   kubelet, ip-10-209-103-40.us-west-2.compute.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "d20eb84d0be212c52e734d4c034f9ea29fb3a98c78d4d4cb111cf536f45298ea" network for pod "<redacted>": networkPlugin cni failed to set up pod "<redacted>" network: hnsCall failed in Win32: An address provided is invalid or reserved. (0x803b002f)
```
K8s version: 1.16
This pod is being scheduled on a Windows Worker Node using the amazon/Windows_Server-1909-English-Core-EKS_Optimized-1.16-2020.06.10 AMI.

We have also observed errors in the CNI logs as follows: 
```
**2020-07-22T19:59:53Z [ERROR] Failed to parse netconfig from args: failed to parse Kubernetes args: failed to get pod settingsapi-test-connection: pods "settingsapi-test-connection" not found.
2020-07-22T19:59:53Z [ERROR] CNI command failed: failed to parse Kubernetes args: failed to get pod settingsapi-test-connection: pods "settingsapi-test-connection" not found
2020-07-22T19:59:53Z [INFO] Plugin vpc-shared-eni version  executing CNI command.
2020-07-22T19:59:53Z [ERROR] Failed to parse netconfig from args: failed to parse Kubernetes args: failed to get pod tmp-shelly3: pods "tmp-shelly3" not found.
2020-07-22T19:59:53Z [ERROR] CNI command failed: failed to parse Kubernetes args: failed to get pod tmp-shelly3: pods "tmp-shelly3" not found
2020-07-22T19:59:53Z [INFO] Plugin vpc-shared-eni version  executing CNI command.
2020-07-22T19:59:53Z [ERROR] Failed to parse netconfig from args: failed to parse Kubernetes args: failed to get pod <redacted>: pods "<redacted>" not found.
2020-07-22T19:59:53Z [ERROR] CNI command failed: failed to parse Kubernetes args: failed to get pod <redacted>: pods "<redacted>" not found
2020-07-22T19:59:58Z [INFO] Plugin vpc-shared-eni version  executing CNI command.
PS C:\ProgramData\Amazon\EKS\logs>
**
```
These errors appear to be referencing pods that no longer exist (and haven't for some time), are repeated constantly, and do not seem to directly correlate in start time to the incident above. The only way to stop the CNI from logging this second set errors seems to be to terminate the node, they even persist through reboot.

I'm happy to provide any more details that I can if needed.

**Comment by abhipth** [comment]
Hello @andrewpurdin thanks for reporting the issue. I was able to reproduce this on my setup by immediately scaling a deployment up and down multiple times.

Add Request to the CNI Plugin with the IP Address allocated from the Pod Object's annotation.
```
  1 2020-07-28T22:32:24Z [INFO] Executing ADD with netconfig: &{NetConf:{CNIVersion:0.3.1 Name:vpc Type:vpc-shared-eni Capabilities:map[] IPAM:{Type:} DNS:{Nameservers:[10.100.0.10] Domain: Search:[defa    ult.svc.cluster.local svc.cluster.local cluster.local] Options:[]}} ENIName: ENIMACAddress:0a:bc:68:ef:38:4c ENIIPAddress:192.168.86.179/19 VPCCIDRs:[{IP:192.168.0.0 Mask:ffff0000}] BridgeType:L3 Br    idgeNetNSPath: IPAddress:192.168.66.171/19 GatewayIPAddress:192.168.64.1 InterfaceType:veth TapUserID:0 Kubernetes:{Namespace:default PodName:win-webserver-75bc4c4c6f-qt6df PodInfraContainerID:6d167    0a74205e02f655fdcc93898b42ab3c8ff5a2b3ae45cc2d0586825e0b8c0 ServiceCIDR:10.100.0.0/16}} ContainerID:6d1670a74205e02f655fdcc93898b42ab3c8ff5a2b3ae45cc2d0586825e0b8c0 Netns:none IfName:eth0 Args:Ignor    eUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=win-webserver-75bc4c4c6f-qt6df;K8S_POD_INFRA_CONTAINER_ID=6d1670a74205e02f655fdcc93898b42ab3c8ff5a2b3ae45cc2d0586825e0b8c0.
```
The next delete request just after 1 seconds throws this error.
```
2 2020-07-28T22:32:25Z [ERROR] Failed to parse netconfig from args: failed to parse Kubernetes args: failed to get pod win-webserver-75bc4c4c6f-qt6df: pods "win-webserver-75bc4c4c6f-qt6df" not found.
```
And I see 40 such errors withing 8 seconds.
```
 grep "failed to get pod win-webserver-75bc4c4c6f-qt6df:" ~/Downloads/vpc-shared-eni.log.2020-07-28-22  | wc -l
      40
``` 
Since the CNI Plugin failed to clean up the HNS endpoint and failed the delete request the kubelet keeps on retrying to delete. 
 
**Root Cause:**
In the CNI Plugin we are trying to get the Pod Object from the API Server and the pod object has already been deleted from etcd so we cannot find the Pod. 

**Fix**
In delete command we don't need to query the API Server to get the pod IP Address from annotation. I can submit a pull request with the fix if someone has not started working on it yet.

In case @andrewpurdin we saw large amount of such failures which may also be causing kubelet to overload and stop responding to kubectl logs etc.

**Comment by andrewpurdin** [comment]
Thank you for the update @abhipth. I'll be looking out for that PR.

**Comment by abhipth** [comment]
After going through the code again, I realized that in the delete CNI command we don't get the IP Address of the pod in the arguments. So we have to store the IP somewhere in order to solve this problem, solution that @SaranBalaji90 suggested.

- Store the container to IP mapping in a file and have a long running daemon like the one we have for Linux (without IPAMD functionality). I think this is the most optimal solution but requires a bit of redesign of how things work currently.

Other solution on similar note that can work with the existing design,
- Store the data in config map in kube-system namespace instead of file and continue using the binary.
- Read the data from docker container label as seen below.
```
docker inspect 800d7bc53f66174ad38465092edbe5d56068af96a0c6041f855b91346142dc52 | findstr "annotation.vpc.amazonaws.com/PrivateIPv4Address"
                "annotation.vpc.amazonaws.com/PrivateIPv4Address": "192.168.151.233/19",
```

@ofiliz @vsiddharth please let me know your thoughts on this!
